# Generated by Django 5.2.3 on 2025-08-05 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Male',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=100, verbose_name='Full Name')),
            ],
        ),
        migrations.CreateModel(
            name='Female',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=100, verbose_name='Full Name')),
                ('male', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mysite.male')),
            ],
        ),
    ]
