# Generated by Django 5.2.3 on 2025-08-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_product_options_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('books', 'Books')], max_length=100, null=True),
        ),
    ]
