# Generated by Django 5.2.3 on 2025-08-05 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_test_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='create',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
