# Generated by Django 5.2.3 on 2025-08-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_test_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='staticfiles/assets/images/banner-01.jpg', upload_to='blogs/images/%y/%m/%d/'),
        ),
    ]
